
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('customers').del()
    .then(function () {
      // Inserts seed entries
      return knex('customers').insert([
        {firstName: 'John',
        lastName: 'Doh',
        emailAddress: 'john@doe.com',
        statusCode: 6},
        {firstName: 'Sue',
        lastName: 'Doh',
        emailAddress: 'sue@doe.com',
        statusCode: 5},
        {firstName: 'Dan',
        lastName: 'Doh',
        emailAddress: 'Dan@doe.com',
        statusCode: 6},
        {firstName: 'Bob',
        lastName: 'Doh',
        emailAddress: 'Bob@doe.com',
        statusCode: 4},
        {firstName: 'Rex',
        lastName: 'Doh',
        emailAddress: 'Rex@doe.com',
        statusCode: 0},
        {firstName: 'Bex',
        lastName: 'Doh',
        emailAddress: 'Bex@doe.com',
        statusCode: 0},
        {firstName: 'Tex',
        lastName: 'Doh',
        emailAddress: 'Tex@doe.com',
        statusCode: 0},
        {firstName: 'Larry',
        lastName: 'Doh',
        emailAddress: 'Larry@doe.com',
        statusCode: 0},
        {firstName: 'Gary',
        lastName: 'Doh',
        emailAddress: 'Gary@doe.com',
        statusCode: 0},
        {firstName: 'Harry',
        lastName: 'Doh',
        emailAddress: 'Harry@doe.com',
        statusCode: 0},
        {firstName: 'Terry',
        lastName: 'Doh',
        emailAddress: 'Terry@doe.com',
        statusCode: 0},
        {firstName: 'Barry',
        lastName: 'Doh',
        emailAddress: 'Barry@doe.com',
        statusCode: 0},
      ]);
    });
};
